name: Chall Intro

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write
  contents: write

jobs:
  access_secret_flag:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repo: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          
      - name: List all secrets (names only)
        run: |
          # Les secrets ne s'affichent pas directement, mais on peut tester leur existence
          if [ -n "${{ secrets.FLAG }}" ]; then echo "FLAG exists!"; fi
